development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://veronicarodriguez.com/faye"
  secret_token: <%= ENV["FAYE"] %>
  signature_expiration: 3600 # one hour
